/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnimatedBackground: typeof import('./../components/AnimatedBackground.vue')['default']
    BgStack: typeof import('./../components/BgStack.vue')['default']
    ChatQueue: typeof import('./../components/ChatQueue.vue')['default']
    DefaultApp: typeof import('./../components/win98/apps/DefaultApp.vue')['default']
    DesktopIcon: typeof import('./../components/win98/DesktopIcon.vue')['default']
    DesktopLayout: typeof import('./../components/win98/DesktopLayout.vue')['default']
    FrameContainer: typeof import('./../components/FrameContainer.vue')['default']
    Live2dCharacter: typeof import('./../components/Live2dCharacter.vue')['default']
    Live2dModel: typeof import('./../components/Live2dModel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusBar: typeof import('./../components/StatusBar.vue')['default']
    Taskbar: typeof import('./../components/win98/Taskbar.vue')['default']
    TitleBar: typeof import('./../components/TitleBar.vue')['default']
    VisualNovel: typeof import('./../components/VisualNovel.vue')['default']
    WelcomeApp: typeof import('./../components/win98/apps/WelcomeApp.vue')['default']
    WindowFrame: typeof import('./../components/win98/WindowFrame.vue')['default']
  }
}
